### ISSUE TITLE
[Bug]: Visit object `visit.from.url` and `visit.to.url` values incorrect on `scroll:end` lifecycle

### ISSUE THREAD

**Issue by elliottmangham** [swup/scroll-plugin#81]
### What did you expect? 🧐

I would expect the following code to contain the correct `visit.from.url` and `visit.to.url` values from the latest page change:
```js
swup.hooks.on('scroll:end', (visit) => {
	console.log(visit);
});
```

### What actually happened? 😵‍💫

The `visit.from.url` and `visit.to.url` values are always the same, even if scrolling on the current page, or between different pages.

The values also appear incorrect, for example, if I navigate from `/` to `/enquire`, both `visit.from.url` and `visit.to.url` values are `/`. If I then navigate from `/enquire` to `/`, both `visit.from.url` and `visit.to.url` values are still `/`. Clicking on a link that has the same `href` value as the current page, also does not output the correct `visit.from.url` and `visit.to.url` values, in such case I would expect the same values.

Screen recording: https://cloud.cdrs.dev/88nSD2Gw

### Swup and plugin versions 📝

@swup/body-class-plugin: 3.2.0
@swup/overlay-theme: 2.0.0
@swup/preload-plugin: 3.2.10
@swup/progress-plugin: 3.2.0
@swup/scripts-plugin: 2.1.0
@swup/scroll-plugin: 3.3.2
swup: 4.6.1

### What browsers are you seeing the problem on? 🧭

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output 🤓

```shell
animation: {animate: true, wait: false, name: undefined, native: false, scope: 'html', …}
cache: {read: true, write: true}
containers: ['#swup']
from: {url: '/'}
history: {action: 'push', popstate: false, direction: undefined}
id: 0.6330202602352362
scroll: {reset: true, target: undefined}
state: 1
to: {url: '/', hash: undefined}
trigger: {el: undefined, event: undefined}
```

### URL to minimal reproduction 🔗

Note: For some reason the console output is not doing anything (sorry, I am new to online sandboxes)

https://codesandbox.io/p/devbox/empty-hill-kgn68f?workspaceId=6b038d9d-3724-456e-99a2-52aa6d31cc98

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Right, that's a bit confusing! You're basically receiving a dummy visit in that hook.

Currently, swup passes a visit object into handlers of all hook types. However, a number of hooks happen outside of a visit, like `cache:clear`, `page:preload`, or `scroll:end` if the scrolling is to an anchor on the same page. Our solution for swup 4 was to provide a fallback or dummy visit object in those cases. In hindsight, we should have made a distinction between hooks that receive a visit object and hooks that don't. [That's on the roadmap for swup 5](https://github.com/orgs/swup/projects/3?pane=issue&itemId=53895943). While this would provide some clarity around when to expect a visit object, it wouldn't help in your use case — the `scroll:end` hook just won't receive a visit object at all. 

You could however use `swup.visit` instead of the local handler argument `visit`. That should always have the current (or most recent) visit, and never a dummy visit.

I'll close this issue as it can only be fixed by a breaking change already on the roadmap, but feel free to comment if the explanation wasn't very clear.

**Comment by elliottmangham** [comment]
Thanks for the response @daun 🙏 I appreciate the deeper understanding!

I will try out `swup.visit` in the meantime to see if that helps.

**Comment by daun** [comment]
`swup.visit` only ever holds visits that cause a navigation, i.e. that load a new page. Scrolling on the same page doesn't cause a visit, hence these hooks only get the aforementioned dummy visit object.

The `content:scroll` hook is probably what you're looking for here. It executes the scroll on the new page (top or anchor), but never to a link on the current page. Inside, you can register a hook handler for `scroll:end` to only run once. It is a bit brittle though, and currently there's no official/straightforward way to do this unless you handle the scrolling yourself. Let us know if the (untested) example works as expected.

```js
swup.hooks.before('content:scroll', () => {
  swup.hooks.once('scroll:end', () => console.log('scrolling finished'))
})
```

The opposite hook would be `link:anchor` which executes when clicking on a same-page link.

**Comment by elliottmangham** [comment]
@daun this is absolutely perfect, thanks for the solid solution 🤌 Sorted.
